/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package template;

import algo.DumbSolver;
import io.input.InstanceFileParser;
import io.input.ParserException;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.util.List;
import model.Depot;
import model.Emplacement;
import model.Instance;
import model.Vehicule;

/**
 *
 * @author thibaut
 */
public class Itineraire extends javax.swing.JFrame {

    /**
     * entre 360 getHSBColor(, 1, 0.8)
     */
    /**
     * Creates new form itineraire
     */
    public Itineraire() {
        this.initComponents();
        this.initialisationFenetre();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Color c = g.getColor();
        // DESSIN D'une Instance
        DumbSolver ds = this.createInstance();
        if (ds == null) {
            return;
        }

        Instance i = ds.getInstance();
        if (i == null) {
            return;
        }

        this.drawInstance(g, i);
        g.setColor(c);

    }

    private void drawEmplacement(Graphics g, Emplacement e) {
        if (e == null) {
            return;
        }

        if (e instanceof Depot) {
            g.setColor(Color.RED);
        } else {
            g.setColor(Color.BLUE);
        }
        g.fillRect((int) e.getX() * 4 + 400 - 3, (int) e.getY() * 4 + 400 - 3, 6, 6);

    }

    private void drawInstance(Graphics g, Instance i) {
        if (i == null) {
            return;
        }
        //Dessin du depot
        Depot d = i.getDepot();

        List<Vehicule> vehicules = i.getVehicules();
        int code = 0;

        for (Vehicule v : vehicules) {
            Emplacement source = d;
            for (Emplacement destination : v.getDestinations()) {
                g.setColor(Color.getHSBColor(code / 360.0f, 1, 0.8f));
                Graphics2D g2 = (Graphics2D) g;
                g2.setStroke(new BasicStroke(3));
                g2.drawLine((int) source.getX() * 4 + 400, (int) source.getY() * 4 + 400, (int) destination.getX() * 4 + 400, (int) destination.getY() * 4 + 400);
                source = destination;
                drawEmplacement(g, destination);

            }
            g.drawLine((int) source.getX() * 4 + 400, (int) source.getY() * 4 + 400, (int) d.getX() * 4 + 400, (int) d.getY() * 4 + 400);
            code += 20;
            System.out.println("code :" + code);
        }
        drawEmplacement(g, d);

    }

    private DumbSolver createInstance() {
        Instance i;
        try {
            InstanceFileParser ifp = new InstanceFileParser();
            i = ifp.parse(new File("src/main/resources/instances/instance_0-triangle.txt"));
        } catch (ParserException ex) {
            ex.printStackTrace();
            return null;
        }
        DumbSolver ds = new DumbSolver(i);
        ds.solve();
        return ds;
    }

    private void initialisationFenetre() {

        this.setVisible(true);
        this.setTitle("Itineraire");
        this.getContentPane().setBackground(Color.white);
        this.setBackground(Color.WHITE);
        this.setPreferredSize(new Dimension(400, 200));
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Itineraire i = new Itineraire();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
