# Java Maven CircleCI 2.0 configuration file
#
version: 2

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-11

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
          
      - run: mvn test
